from app.models.user import User
from app.models.plot import Plot
from app.models.floor import Floor
from app.models.rm import RelationshipManager
from app.models.broker import Broker
from app.models.customer import Customer
from app.models.sale import Sale
from app.models.payment import Payment
from app.models.document import Document